export const strings = {
  app: {
    name: 'JOKGER',
    operationTitle: 'Operasional',
    loading: 'Memuat aplikasi',
    loadError: 'Aplikasi tidak dapat dimuat.',
  },
  common: {
    skipToContent: 'Lewati ke konten utama',
    retry: 'Coba lagi',
    save: 'Simpan',
    confirm: 'Konfirmasi',
    cancel: 'Batal',
    reason: 'Alasan',
    typeToConfirm: 'Ketik teks konfirmasi',
    loading: 'Memuat…',
    rupiah: 'rupiah',
    unknownError: 'Terjadi kesalahan. Coba lagi.',
    configurationError: 'Aplikasi belum terhubung ke layanan. Hubungi pemilik.',
  },
  auth: {
    loginTitle: 'Masuk ke JOKGER',
    loading: 'Memeriksa sesi',
    email: 'Email',
    password: 'Kata sandi',
    login: 'Masuk',
    loggingIn: 'Memeriksa akun…',
    forgotPassword: 'Lupa kata sandi?',
    resetPasswordSent: 'Jika alamat tersebut terdaftar, petunjuk pemulihan akan dikirim.',
    emailInvalid: 'Masukkan alamat email yang valid.',
    passwordRequired: 'Kata sandi wajib diisi.',
    lockout: 'Coba lagi dalam',
    secondsSuffix: 'detik',
    invalidCredentials: 'Email atau kata sandi salah.',
    inactiveAccount: 'Akun Anda tidak aktif. Hubungi pemilik.',
    sessionExpired: 'Sesi berakhir. Masuk kembali.',
    sessionIdle: 'Sesi berakhir karena tidak ada aktivitas.',
  },
  shift: {
    title: 'Shift kasir',
    openingTitle: 'Buka kasir',
    openingCash: 'Saldo awal tunai',
    open: 'Buka kasir',
    opening: 'Membuka kasir…',
    activeTitle: 'Kasir sedang terbuka',
    openedAt: 'Dibuka pada',
    expectedCash: 'Kas yang diharapkan',
    actualCash: 'Kas fisik',
    difference: 'Selisih kas',
    close: 'Tutup kasir',
    closing: 'Menutup kasir…',
    closeDescription: 'Pastikan jumlah uang fisik sudah dihitung sebelum menutup shift.',
    closeNote: 'Catatan',
    cashRequired: 'Masukkan jumlah kas fisik.',
    noOpenShift: 'Belum ada shift kasir yang terbuka.',
    loadError: 'Informasi shift tidak dapat dimuat.',
    openSuccess: 'Kasir berhasil dibuka.',
    closeSuccess: 'Kasir berhasil ditutup.',
    confirmClose: 'Konfirmasi tutup kasir',
    closeTitle: 'Tutup kasir sekarang?',
    closeReview: 'Periksa jumlah kas fisik dan konfirmasi penutupan shift.',
    openBillWarning: 'Masih ada open bill di shift ini.',
    cancel: 'Batal',
  },
  pos: {
    title: 'Kasir',
    categories: 'Kategori menu',
    allCategories: 'Semua menu',
    search: 'Cari menu',
    cart: 'Keranjang',
    emptyCart: 'Keranjang masih kosong.',
    addMenu: 'Pilih menu untuk memulai pesanan.',
    soldOut: 'Habis',
    dineIn: 'Makan di tempat',
    takeaway: 'Bawa pulang',
    orderType: 'Jenis pesanan',
    table: 'Nomor meja',
    customer: 'Nama pelanggan',
    note: 'Catatan',
    subtotal: 'Subtotal',
    serviceFee: 'Layanan',
    tax: 'Pajak',
    rounding: 'Pembulatan',
    total: 'Total',
    clearCart: 'Kosongkan keranjang',
    clearCartTitle: 'Kosongkan keranjang?',
    clearCartDescription: 'Semua item dan pilihan pesanan saat ini akan dihapus.',
    pay: 'Bayar',
    payment: 'Pembayaran tunai',
    paymentMethod: 'Metode pembayaran',
    cash: 'Tunai',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    paymentAccount: 'Rekening tujuan',
    copyAccount: 'Salin nomor',
    accountCopied: 'Nomor rekening disalin.',
    paymentReference: 'Nomor referensi',
    noPaymentAccounts: 'Belum ada rekening aktif untuk metode ini.',
    submitForVerification: 'Kirim untuk verifikasi',
    amountReceived: 'Uang diterima',
    change: 'Kembalian',
    shortfall: 'Kurang',
    finishPayment: 'Selesaikan pembayaran',
    processingPayment: 'Menyimpan pesanan…',
    cancelPayment: 'Kembali ke keranjang',
    paymentSuccess: 'Pesanan berhasil dibuat.',
    orderNumber: 'Nomor pesanan',
    newOrder: 'Pesanan baru',
    modifierTitle: 'Pilih tambahan',
    modifierRulesSingle: 'Pilih satu',
    modifierRulesMultiple: 'Pilih hingga',
    addToCart: 'Tambah ke keranjang',
    decreaseQty: 'Kurangi jumlah',
    increaseQty: 'Tambah jumlah',
    undo: 'Urungkan',
    removedLine: 'Item dihapus dari keranjang.',
    connection: 'Koneksi',
    online: 'Online',
    offline: 'Offline',
    noCategories: 'Belum ada kategori menu aktif.',
    noMenuItems: 'Belum ada menu aktif di kategori ini.',
    menuLoadError: 'Menu tidak dapat dimuat.',
    connectionError: 'Periksa koneksi sebelum menyimpan pesanan.',
    priceChanged: 'Harga menu berubah. Keranjang dipertahankan; periksa total baru.',
    menuAvailableChanged: 'Menu diperbarui. Periksa kembali pilihan dan total.',
    checkoutError: 'Pesanan belum tersimpan. Keranjang tetap tersedia untuk dicoba lagi.',
  },
  orders: {
    title: 'Pesanan',
    all: 'Semua',
    new: 'Baru',
    processing: 'Diproses',
    ready: 'Menunggu diambil',
    completed: 'Selesai',
    cancelled: 'Dibatalkan',
    noOrders: 'Belum ada pesanan aktif.',
    loadError: 'Daftar pesanan tidak dapat dimuat.',
    process: 'Proses',
    markReady: 'Tandai siap',
    complete: 'Selesaikan',
    cancel: 'Batalkan pesanan',
    cancelTitle: 'Batalkan pesanan',
    cancelDescription:
      'Stok akan dikembalikan dan pembayaran terverifikasi akan dicatat sebagai refund.',
    elapsed: 'Dibuat',
    realtime: 'Langsung',
    autoRefresh: 'Muat ulang otomatis',
    dineIn: 'Makan di tempat',
    takeaway: 'Bawa pulang',
    openBill: 'Open bill',
    shortWait: 'Pesanan baru',
    errorPayment: 'Pembayaran belum lunas atau belum diverifikasi.',
  },
  inventory: {
    title: 'Inventaris',
    name: 'Nama bahan',
    unit: 'Satuan',
    currentStock: 'Stok saat ini',
    minimumStock: 'Stok minimum',
    stockValue: 'Nilai stok',
    status: 'Kondisi',
    safe: 'Aman',
    low: 'Menipis',
    empty: 'Habis',
    noItems: 'Belum ada bahan inventaris aktif.',
    loadError: 'Inventaris tidak dapat dimuat.',
    purchase: 'Catat pembelian',
    waste: 'Catat waste',
    adjustment: 'Penyesuaian stok',
    quantity: 'Jumlah',
    note: 'Catatan',
    reason: 'Alasan',
    submitMovement: 'Simpan pergerakan',
    addItem: 'Tambah bahan',
    editItem: 'Ubah bahan',
    saveItem: 'Simpan bahan',
    itemSaved: 'Bahan berhasil disimpan.',
    saveItemError: 'Bahan belum tersimpan.',
    itemName: 'Nama bahan',
    unitCost: 'Harga pokok per satuan',
    movementTitle: 'Catat pergerakan stok',
    confirmMovement: 'Simpan perubahan stok?',
    negativeTitle: 'Izinkan stok negatif?',
    negativeHint: 'Tindakan ini memerlukan alasan dan konfirmasi nama bahan.',
    allowNegative: 'Izinkan stok menjadi negatif',
    typeItemName: 'Ketik nama bahan',
    movementSaved: 'Pergerakan stok berhasil dicatat.',
    movementError: 'Pergerakan stok belum tersimpan.',
    stockNegative: 'Stok tidak boleh menjadi negatif.',
  },
  paymentVerification: {
    title: 'Verifikasi pembayaran',
    queue: 'Menunggu verifikasi',
    empty: 'Tidak ada pembayaran yang menunggu verifikasi.',
    loadError: 'Antrian verifikasi tidak dapat dimuat.',
    selectPayment: 'Pilih pembayaran untuk diperiksa.',
    amount: 'Nominal',
    order: 'Nomor pesanan',
    method: 'Metode',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    account: 'Rekening tujuan',
    reference: 'Nomor referensi',
    submittedAt: 'Dikirim pada',
    proofMissing: 'Bukti belum dilampirkan.',
    approve: 'Setujui',
    reject: 'Tolak',
    approveTitle: 'Setujui pembayaran ini?',
    approveDescription: 'Pastikan nominal dan tujuan pembayaran sudah sesuai.',
    rejectTitle: 'Tolak pembayaran ini?',
    rejectDescription: 'Alasan penolakan wajib dicatat.',
    approved: 'Pembayaran berhasil disetujui.',
    rejected: 'Pembayaran berhasil ditolak.',
    loadProofError: 'Bukti pembayaran tidak dapat dibuka.',
    openProof: 'Buka bukti di tab baru',
  },
  paymentAccounts: {
    title: 'Rekening pembayaran',
    empty: 'Belum ada rekening pembayaran.',
    add: 'Tambah rekening',
    edit: 'Ubah rekening',
    save: 'Simpan rekening',
    method: 'Metode',
    provider: 'Penyedia',
    accountName: 'Nama pemilik',
    accountNumber: 'Nomor rekening',
    sortOrder: 'Urutan',
    active: 'Aktif',
    inactive: 'Nonaktif',
    maskedPrefix: '•••• ',
    activate: 'Aktifkan',
    deactivate: 'Nonaktifkan',
    deactivateTitle: 'Nonaktifkan rekening ini?',
    deactivateDescription: 'Rekening ini tidak lagi tersedia untuk pembayaran baru.',
    saved: 'Rekening berhasil disimpan.',
    saveError: 'Rekening belum tersimpan.',
  },
  errors: {
    NOT_AUTHORIZED: 'Anda tidak punya hak untuk tindakan ini.',
    INPUT_INVALID: 'Periksa kembali informasi yang dimasukkan.',
    SHIFT_NOT_OPEN: 'Belum ada shift terbuka.',
    SHIFT_ALREADY_OPEN: 'Sudah ada shift kasir yang terbuka.',
    SHIFT_NOT_FOUND: 'Shift tidak ditemukan.',
    SHIFT_HAS_OPEN_BILL: 'Tutup semua open bill terlebih dahulu.',
    ORDER_NOT_FOUND: 'Pesanan tidak ditemukan.',
    ORDER_STATUS_TRANSITION_INVALID: 'Perubahan status pesanan tidak diizinkan.',
    ORDER_NOT_CANCELLABLE: 'Pesanan tidak dapat dibatalkan pada status ini.',
    ORDER_NOT_RETURNABLE: 'Pesanan tidak dapat diretur.',
    BILL_CLOSED: 'Open bill sudah ditutup.',
    BILL_NOT_CLOSED: 'Bill belum ditutup.',
    BILL_EMPTY: 'Tambahkan item sebelum menutup bill.',
    MENU_ITEM_UNAVAILABLE: 'Menu tidak tersedia atau sedang habis.',
    ITEM_INVALID: 'Item pesanan tidak valid.',
    ITEM_QUANTITY_INVALID: 'Jumlah item harus antara 1 sampai 100.',
    ITEM_NOT_FOUND: 'Item pesanan tidak ditemukan.',
    ITEM_ALREADY_VOIDED: 'Item sudah dibatalkan.',
    MODIFIER_INVALID: 'Pilihan tambahan menu tidak valid.',
    STOCK_INSUFFICIENT: 'Stok bahan tidak mencukupi.',
    VOUCHER_NOT_FOUND: 'Kode voucher tidak ditemukan.',
    VOUCHER_INACTIVE: 'Voucher sedang tidak aktif.',
    VOUCHER_NOT_STARTED: 'Voucher belum mulai berlaku.',
    VOUCHER_EXPIRED: 'Masa berlaku voucher sudah berakhir.',
    VOUCHER_QUOTA_EXCEEDED: 'Kuota voucher sudah habis.',
    VOUCHER_MIN_SUBTOTAL: 'Belum memenuhi minimum belanja voucher.',
    VOUCHER_ALREADY_APPLIED: 'Pesanan sudah memakai voucher.',
    PAYMENT_AMOUNT_INVALID: 'Nominal pembayaran tidak valid.',
    PAYMENT_EXCEEDS_OUTSTANDING: 'Nominal pembayaran melebihi tagihan.',
    PAYMENT_ACCOUNT_INVALID: 'Rekening tidak aktif atau tidak sesuai metode.',
    PAYMENT_NOT_FOUND: 'Pembayaran tidak ditemukan.',
    PAYMENT_NOT_PENDING: 'Pembayaran sudah diverifikasi atau ditolak.',
    PAYMENT_NOT_VERIFIED: 'Pembayaran belum lunas atau belum terverifikasi.',
    CASH_RECEIVED_INSUFFICIENT: 'Uang yang diterima belum mencukupi tagihan.',
    REASON_REQUIRED: 'Alasan wajib diisi.',
    OPNAME_FINALIZED: 'Stok opname sudah difinalisasi.',
    OPNAME_NOT_FOUND: 'Stok opname tidak ditemukan.',
    OPNAME_ALREADY_DRAFT: 'Masih ada stok opname yang sedang berjalan.',
    STAFF_NOT_FOUND: 'Staff tidak ditemukan.',
    SELF_ROLE_CHANGE_FORBIDDEN: 'Anda tidak dapat mengubah peran sendiri.',
    SELF_DEACTIVATION_FORBIDDEN: 'Anda tidak dapat menonaktifkan akun sendiri.',
    LAST_SUPER_ADMIN: 'Super admin terakhir tidak dapat dinonaktifkan atau diturunkan perannya.',
    SETTINGS_INVALID: 'Pengaturan tidak valid.',
    CONTRAST_TOO_LOW: 'Kontras warna di bawah standar aksesibilitas.',
    STAFF_EMAIL_EXISTS: 'Email sudah terdaftar.',
    SERVER_NOT_CONFIGURED: 'Konfigurasi layanan belum lengkap. Hubungi pemilik.',
    NETWORK_OFFLINE: 'Koneksi internet terputus.',
    REQUEST_TIMEOUT: 'Koneksi lambat. Coba lagi.',
    UNKNOWN: 'Terjadi kesalahan. Coba lagi.',
    INVALID_CREDENTIALS: 'Email atau kata sandi salah.',
    NOT_FOUND: 'Halaman tidak ditemukan.',
    forbiddenTitle: 'Anda tidak punya akses.',
    backToShift: 'Kembali ke shift kasir',
  },
} as const;
