export const strings = {
  app: {
    name: 'JOKGER',
    operationTitle: 'Operasional',
    loading: 'Memuat aplikasi',
    loadError: 'Aplikasi tidak dapat dimuat.',
  },
  common: {
    skipToContent: 'Lewati ke konten utama',
    retry: 'Coba lagi',
    save: 'Simpan',
    confirm: 'Konfirmasi',
    cancel: 'Batal',
    reason: 'Alasan',
    typeToConfirm: 'Ketik teks konfirmasi',
    loading: 'Memuat…',
    rupiah: 'rupiah',
    unknownError: 'Terjadi kesalahan. Coba lagi.',
    configurationError: 'Aplikasi belum terhubung ke layanan. Hubungi pemilik.',
    unsavedChanges: 'Ada perubahan yang belum tersimpan. Tetap tinggalkan halaman ini?',
  },
  auth: {
    loginTitle: 'Masuk ke JOKGER',
    loading: 'Memeriksa sesi',
    email: 'Email',
    password: 'Kata sandi',
    login: 'Masuk',
    loggingIn: 'Memeriksa akun…',
    forgotPassword: 'Lupa kata sandi?',
    resetPasswordSent: 'Jika alamat tersebut terdaftar, petunjuk pemulihan akan dikirim.',
    emailInvalid: 'Masukkan alamat email yang valid.',
    passwordRequired: 'Kata sandi wajib diisi.',
    passwordChangeTitle: 'Ganti kata sandi',
    passwordChangeDescription: 'Gunakan kata sandi baru yang hanya Anda ketahui.',
    passwordCurrent: 'Kata sandi saat ini',
    passwordNew: 'Kata sandi baru',
    passwordConfirm: 'Ulangi kata sandi baru',
    passwordCurrentRequired: 'Masukkan kata sandi saat ini.',
    passwordCurrentInvalid: 'Kata sandi saat ini tidak sesuai.',
    passwordTooShort: 'Kata sandi baru minimal 10 karakter.',
    passwordTooLong: 'Kata sandi baru maksimal 128 karakter.',
    passwordConfirmRequired: 'Ulangi kata sandi baru.',
    passwordMismatch: 'Kata sandi baru belum sama.',
    passwordMustChange: 'Kata sandi baru harus berbeda dari kata sandi saat ini.',
    passwordChangeSubmit: 'Simpan kata sandi baru',
    passwordChanging: 'Menyimpan kata sandi…',
    passwordChanged: 'Kata sandi berhasil diganti.',
    passwordChangeFailed: 'Kata sandi belum berhasil diganti.',
    backToOperations: 'Kembali ke operasional',
    lockout: 'Coba lagi dalam',
    secondsSuffix: 'detik',
    invalidCredentials: 'Email atau kata sandi salah.',
    inactiveAccount: 'Akun Anda tidak aktif. Hubungi pemilik.',
    sessionExpired: 'Sesi berakhir. Masuk kembali.',
    sessionIdle: 'Sesi berakhir karena tidak ada aktivitas.',
  },
  shift: {
    title: 'Shift kasir',
    openingTitle: 'Buka kasir',
    openingCash: 'Saldo awal tunai',
    open: 'Buka kasir',
    opening: 'Membuka kasir…',
    activeTitle: 'Kasir sedang terbuka',
    openedAt: 'Dibuka pada',
    expectedCash: 'Kas yang diharapkan',
    actualCash: 'Kas fisik',
    difference: 'Selisih kas',
    close: 'Tutup kasir',
    closing: 'Menutup kasir…',
    closeDescription: 'Pastikan jumlah uang fisik sudah dihitung sebelum menutup shift.',
    closeNote: 'Catatan',
    cashRequired: 'Masukkan jumlah kas fisik.',
    noOpenShift: 'Belum ada shift kasir yang terbuka.',
    loadError: 'Informasi shift tidak dapat dimuat.',
    openSuccess: 'Kasir berhasil dibuka.',
    closeSuccess: 'Kasir berhasil ditutup.',
    confirmClose: 'Konfirmasi tutup kasir',
    closeTitle: 'Tutup kasir sekarang?',
    closeReview: 'Periksa jumlah kas fisik dan konfirmasi penutupan shift.',
    openBillWarning: 'Masih ada open bill di shift ini.',
    cancel: 'Batal',
  },
  pos: {
    title: 'Kasir',
    categories: 'Kategori menu',
    allCategories: 'Semua menu',
    search: 'Cari menu',
    cart: 'Keranjang',
    emptyCart: 'Keranjang masih kosong.',
    addMenu: 'Pilih menu untuk memulai pesanan.',
    soldOut: 'Habis',
    dineIn: 'Makan di tempat',
    takeaway: 'Bawa pulang',
    orderType: 'Jenis pesanan',
    table: 'Nomor meja',
    customer: 'Nama pelanggan',
    voucher: 'Kode voucher',
    applyVoucher: 'Terapkan',
    removeVoucher: 'Hapus voucher',
    voucherDiscount: 'Diskon voucher',
    note: 'Catatan',
    subtotal: 'Subtotal',
    serviceFee: 'Layanan',
    tax: 'Pajak',
    rounding: 'Pembulatan',
    total: 'Total',
    clearCart: 'Kosongkan keranjang',
    clearCartTitle: 'Kosongkan keranjang?',
    clearCartDescription: 'Semua item dan pilihan pesanan saat ini akan dihapus.',
    pay: 'Bayar',
    openBill: 'Buka bill',
    payment: 'Pembayaran tunai',
    paymentMethod: 'Metode pembayaran',
    cash: 'Tunai',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    paymentAccount: 'Rekening tujuan',
    copyAccount: 'Salin nomor',
    accountCopied: 'Nomor rekening disalin.',
    paymentReference: 'Nomor referensi',
    noPaymentAccounts: 'Belum ada rekening aktif untuk metode ini.',
    submitForVerification: 'Kirim untuk verifikasi',
    amountReceived: 'Uang diterima',
    change: 'Kembalian',
    shortfall: 'Kurang',
    finishPayment: 'Selesaikan pembayaran',
    processingPayment: 'Menyimpan pesanan…',
    cancelPayment: 'Kembali ke keranjang',
    paymentSuccess: 'Pesanan berhasil dibuat.',
    orderNumber: 'Nomor pesanan',
    newOrder: 'Pesanan baru',
    modifierTitle: 'Pilih tambahan',
    modifierRulesSingle: 'Pilih satu',
    modifierRulesMultiple: 'Pilih hingga',
    addToCart: 'Tambah ke keranjang',
    decreaseQty: 'Kurangi jumlah',
    increaseQty: 'Tambah jumlah',
    undo: 'Urungkan',
    removedLine: 'Item dihapus dari keranjang.',
    connection: 'Koneksi',
    online: 'Online',
    offline: 'Offline',
    noCategories: 'Belum ada kategori menu aktif.',
    noMenuItems: 'Belum ada menu aktif di kategori ini.',
    menuLoadError: 'Menu tidak dapat dimuat.',
    connectionError: 'Periksa koneksi sebelum menyimpan pesanan.',
    priceChanged: 'Harga menu berubah. Keranjang dipertahankan; periksa total baru.',
    menuAvailableChanged: 'Menu diperbarui. Periksa kembali pilihan dan total.',
    checkoutError: 'Pesanan belum tersimpan. Keranjang tetap tersedia untuk dicoba lagi.',
  },
  openBill: {
    title: 'Open bill',
    loadError: 'Open bill tidak dapat dimuat.',
    notFound: 'Bill tidak ditemukan.',
    openedAt: 'Dibuka',
    viewOrder: 'Lihat pesanan',
    closed: 'Bill sudah ditutup.',
    readOnly: 'Bill ini hanya dapat dilihat dan tidak menerima perubahan lagi.',
    notOpenBill: 'Pesanan ini bukan open bill.',
    notOpenBillDescription: 'Buka detail pesanan untuk melihat informasi dan pembayarannya.',
    shiftClosed: 'Shift bill ini sudah ditutup.',
    shiftClosedDescription:
      'Bill tidak dapat diubah karena bukan bagian dari shift yang sedang terbuka.',
    addItems: 'Tambah menu ke bill',
    staged: 'Item untuk ditambahkan',
    removeStaged: 'Hapus',
    addToBill: 'Tambah ke bill',
    itemsAdded: 'Item berhasil ditambahkan ke bill.',
    itemsNotAdded: 'Belum tersimpan',
    bill: 'Bill',
    addedAt: 'Ditambahkan',
    sent: 'Sudah dikirim',
    total: 'Total sementara',
    closeBill: 'Tutup bill',
    split: 'Split payment',
    selectAccount: 'Pilih rekening',
    paymentLine: 'Baris pembayaran',
    removePaymentLine: 'Hapus baris',
    addPaymentLine: 'Tambah baris pembayaran',
    remaining: 'Sisa tagihan',
    voidItem: 'Void item',
    voidTitle: 'Void item bill',
    voidDescription: 'Item akan ditandai void dan stok resep dikembalikan. Alasan wajib diisi.',
    itemVoided: 'Item bill berhasil di-void.',
  },
  orders: {
    title: 'Pesanan',
    all: 'Semua',
    new: 'Baru',
    processing: 'Diproses',
    ready: 'Menunggu diambil',
    completed: 'Selesai',
    cancelled: 'Dibatalkan',
    noOrders: 'Belum ada pesanan aktif.',
    loadError: 'Daftar pesanan tidak dapat dimuat.',
    process: 'Proses',
    markReady: 'Tandai siap',
    complete: 'Selesaikan',
    cancel: 'Batalkan pesanan',
    cancelSuccess: 'Pesanan berhasil dibatalkan.',
    viewDetails: 'Lihat detail pesanan',
    return: 'Retur pesanan',
    cancelTitle: 'Batalkan pesanan',
    cancelDescription:
      'Stok akan dikembalikan dan pembayaran terverifikasi akan dicatat sebagai refund.',
    returnTitle: 'Retur pesanan selesai',
    returnDescription:
      'Stok akan dikembalikan dan pembayaran terverifikasi akan dicatat sebagai refund. Ketik nomor pesanan untuk melanjutkan.',
    returned: 'Retur pesanan berhasil dicatat.',
    elapsed: 'Dibuat',
    realtime: 'Langsung',
    autoRefresh: 'Muat ulang otomatis',
    dineIn: 'Makan di tempat',
    takeaway: 'Bawa pulang',
    openBill: 'Open bill',
    shortWait: 'Pesanan baru',
    errorPayment: 'Pembayaran belum lunas atau belum diverifikasi.',
  },
  orderDetail: {
    loadError: 'Detail pesanan tidak dapat dimuat.',
    notFound: 'Pesanan tidak ditemukan.',
    backToOrders: 'Kembali ke pesanan',
    summary: 'Informasi pesanan',
    createdAt: 'Waktu dibuat',
    createdBy: 'Kasir',
    unknownStaff: 'Staff tidak tersedia',
    orderType: 'Jenis pesanan',
    customer: 'Meja atau pelanggan',
    notProvided: 'Tidak dicantumkan',
    billState: 'Status bill',
    billOpen: 'Terbuka',
    billClosed: 'Ditutup',
    items: 'Rincian item',
    item: 'Item',
    quantity: 'Jumlah',
    unitPrice: 'Harga satuan',
    lineTotal: 'Total baris',
    voided: 'Dibatalkan',
    totals: 'Rincian pembayaran',
    discount: 'Diskon voucher',
    verified: 'Pembayaran terverifikasi',
    pending: 'Menunggu verifikasi',
    remaining: 'Sisa tagihan',
    payments: 'Pembayaran',
    paymentMethod: 'Metode',
    paymentAccount: 'Rekening',
    reference: 'Referensi',
    paymentStatus: 'Status',
    amount: 'Nominal',
    refund: 'Refund',
    noPayments: 'Belum ada pembayaran untuk pesanan ini.',
    notApplicable: '—',
    methods: { cash: 'Tunai', transfer: 'Transfer', ewallet: 'E-wallet' },
    verify: 'Buka verifikasi',
    statusHistory: 'Riwayat pesanan',
    noStatusHistory: 'Riwayat perubahan belum tersedia.',
    created: 'Pesanan dibuat',
    statusChanged: 'Status berubah',
    cancelled: 'Pesanan dibatalkan',
    returned: 'Pesanan diretur',
    itemVoided: 'Item dibatalkan',
    otherChange: 'Pesanan diperbarui',
    unknownStatus: 'Status tidak diketahui',
  },
  history: {
    title: 'Riwayat transaksi',
    filters: 'Filter riwayat transaksi',
    datePresets: 'Periode cepat',
    today: 'Hari ini',
    last7Days: '7 hari',
    thisMonth: 'Bulan ini',
    from: 'Dari tanggal',
    to: 'Sampai tanggal',
    status: 'Status',
    method: 'Metode pembayaran',
    orderType: 'Jenis pesanan',
    cashier: 'Kasir',
    all: 'Semua',
    search: 'Cari nomor pesanan',
    searchPlaceholder: 'Contoh: JKG-20261009',
    apply: 'Terapkan',
    noResults: 'Tidak ada transaksi untuk filter ini.',
    loadError: 'Riwayat transaksi tidak dapat dimuat.',
    resultCount: 'Jumlah transaksi',
    createdAt: 'Waktu',
    items: 'Ringkasan item',
    total: 'Total',
    notApplicable: '—',
    export: 'Unduh CSV',
    exporting: 'Menyiapkan CSV…',
    exported: 'Ekspor riwayat berhasil dibuat.',
    exportTooLarge: 'Persempit filter hingga maksimal 5.000 pesanan sebelum mengekspor.',
    methods: { cash: 'Tunai', transfer: 'Transfer', ewallet: 'E-wallet' },
  },
  inventory: {
    title: 'Inventaris',
    name: 'Nama bahan',
    unit: 'Satuan',
    currentStock: 'Stok saat ini',
    minimumStock: 'Stok minimum',
    stockValue: 'Nilai stok',
    status: 'Kondisi',
    safe: 'Aman',
    low: 'Menipis',
    empty: 'Habis',
    noItems: 'Belum ada bahan inventaris aktif.',
    loadError: 'Inventaris tidak dapat dimuat.',
    purchase: 'Catat pembelian',
    waste: 'Catat waste',
    adjustment: 'Penyesuaian stok',
    quantity: 'Jumlah',
    note: 'Catatan',
    reason: 'Alasan',
    submitMovement: 'Simpan pergerakan',
    addItem: 'Tambah bahan',
    editItem: 'Ubah bahan',
    saveItem: 'Simpan bahan',
    itemSaved: 'Bahan berhasil disimpan.',
    saveItemError: 'Bahan belum tersimpan.',
    itemName: 'Nama bahan',
    unitCost: 'Harga pokok per satuan',
    movementTitle: 'Catat pergerakan stok',
    confirmMovement: 'Simpan perubahan stok?',
    negativeTitle: 'Izinkan stok negatif?',
    negativeHint: 'Tindakan ini memerlukan alasan dan konfirmasi nama bahan.',
    allowNegative: 'Izinkan stok menjadi negatif',
    typeItemName: 'Ketik nama bahan',
    movementSaved: 'Pergerakan stok berhasil dicatat.',
    movementError: 'Pergerakan stok belum tersimpan.',
    stockNegative: 'Stok tidak boleh menjadi negatif.',
  },
  opname: {
    title: 'Stok opname',
    start: 'Mulai opname',
    draftRunning: 'Opname draft sedang berjalan',
    emptyTitle: 'Belum ada stok opname.',
    emptyDescription: 'Mulai opname untuk mencocokkan stok fisik dengan catatan inventaris.',
    loadError: 'Stok opname tidak dapat dimuat.',
    notFound: 'Stok opname tidak ditemukan.',
    backToList: 'Kembali ke daftar opname',
    openedAt: 'Tanggal dibuka',
    openedBy: 'Dibuka oleh',
    status: 'Status',
    draft: 'Berjalan',
    finalized: 'Difinalisasi',
    finalizedAt: 'Tanggal finalisasi',
    summary: 'Ringkasan stok opname',
    materials: 'Bahan',
    differences: 'Bahan berselisih',
    differenceValue: 'Nilai selisih',
    uncounted: 'Belum dihitung',
    systemStock: 'Stok sistem',
    countedStock: 'Stok hitung',
    difference: 'Selisih',
    notCounted: 'Belum dihitung',
    filters: 'Filter bahan opname',
    all: 'Semua bahan',
    onlyDifferences: 'Hanya selisih',
    onlyUncounted: 'Belum dihitung',
    search: 'Cari bahan',
    noMaterials: 'Tidak ada bahan aktif untuk dihitung.',
    noFilterResults: 'Tidak ada bahan yang cocok dengan filter.',
    saving: 'Menyimpan…',
    saved: 'Tersimpan',
    unsaved: 'Menunggu disimpan…',
    saveFailed: 'Gagal menyimpan',
    finalize: 'Finalisasi',
    finalizeTitle: 'Finalisasi opname sekarang?',
    finalizeDescription:
      'Tindakan ini akan menerapkan seluruh selisih stok dan mengunci opname. Bahan berselisih:',
    finalizedBanner: 'Opname sudah difinalisasi pada',
  },
  paymentVerification: {
    title: 'Verifikasi pembayaran',
    queue: 'Menunggu verifikasi',
    empty: 'Tidak ada pembayaran yang menunggu verifikasi.',
    loadError: 'Antrian verifikasi tidak dapat dimuat.',
    selectPayment: 'Pilih pembayaran untuk diperiksa.',
    amount: 'Nominal',
    order: 'Nomor pesanan',
    method: 'Metode',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    account: 'Rekening tujuan',
    reference: 'Nomor referensi',
    submittedAt: 'Dikirim pada',
    proofMissing: 'Bukti belum dilampirkan.',
    approve: 'Setujui',
    reject: 'Tolak',
    approveTitle: 'Setujui pembayaran ini?',
    approveDescription: 'Pastikan nominal dan tujuan pembayaran sudah sesuai.',
    rejectTitle: 'Tolak pembayaran ini?',
    rejectDescription: 'Alasan penolakan wajib dicatat.',
    approved: 'Pembayaran berhasil disetujui.',
    rejected: 'Pembayaran berhasil ditolak.',
    loadProofError: 'Bukti pembayaran tidak dapat dibuka.',
    openProof: 'Buka bukti di tab baru',
  },
  paymentAccounts: {
    title: 'Rekening pembayaran',
    empty: 'Belum ada rekening pembayaran.',
    add: 'Tambah rekening',
    edit: 'Ubah rekening',
    save: 'Simpan rekening',
    method: 'Metode',
    provider: 'Penyedia',
    accountName: 'Nama pemilik',
    accountNumber: 'Nomor rekening',
    sortOrder: 'Urutan',
    active: 'Aktif',
    inactive: 'Nonaktif',
    maskedPrefix: '•••• ',
    activate: 'Aktifkan',
    deactivate: 'Nonaktifkan',
    deactivateTitle: 'Nonaktifkan rekening ini?',
    deactivateDescription: 'Rekening ini tidak lagi tersedia untuk pembayaran baru.',
    saved: 'Rekening berhasil disimpan.',
    saveError: 'Rekening belum tersimpan.',
  },
  vouchers: {
    title: 'Voucher',
    empty: 'Belum ada voucher.',
    add: 'Tambah voucher',
    edit: 'Ubah',
    code: 'Kode',
    name: 'Nama voucher',
    type: 'Jenis potongan',
    percent: 'Persentase',
    nominal: 'Nominal',
    value: 'Nilai potongan',
    minSubtotal: 'Minimum belanja',
    maxDiscount: 'Batas maksimal potongan',
    validFrom: 'Mulai berlaku',
    validUntil: 'Berakhir',
    quota: 'Kuota',
    period: 'Periode',
    status: 'Status',
    actions: 'Aksi',
    active: 'Aktif',
    inactive: 'Nonaktif',
    notStarted: 'Belum berlaku',
    expired: 'Kedaluwarsa',
    quotaUsed: 'Kuota habis',
    unlimited: 'Tanpa batas',
    generate: 'Buat acak',
    previewSubtotal: 'Contoh belanja',
    previewDiscount: 'Potongan',
    previewTotal: 'Total setelah potongan',
    saved: 'Voucher berhasil disimpan.',
    loadError: 'Daftar voucher tidak dapat dimuat.',
    percentInvalid: 'Persentase harus antara 1 sampai 100.',
    invalidCode: 'Kode harus 3 sampai 32 karakter: huruf, angka, atau tanda hubung.',
    invalidName: 'Nama voucher wajib diisi dan maksimal 100 karakter.',
    invalidValue: 'Nilai potongan harus berupa bilangan bulat lebih dari nol.',
    invalidMinSubtotal: 'Minimum belanja harus berupa rupiah bulat dan tidak negatif.',
    maxDiscountPercentOnly: 'Batas maksimal hanya berlaku untuk voucher persentase.',
    invalidMaxDiscount: 'Batas potongan harus lebih dari nol.',
    invalidQuota: 'Kuota harus berupa bilangan bulat lebih dari nol.',
    invalidPeriod: 'Waktu akhir harus setelah waktu mulai.',
    activate: 'Aktifkan',
    deactivate: 'Nonaktifkan',
    activateTitle: 'Aktifkan voucher?',
    deactivateTitle: 'Nonaktifkan voucher?',
    toggleDescription: 'Status voucher akan diperbarui untuk penggunaan berikutnya.',
  },
  menuManagement: {
    title: 'Menu dan kategori',
    categories: 'Kategori',
    items: 'Daftar menu',
    addCategory: 'Tambah kategori',
    addItem: 'Tambah menu',
    editItem: 'Ubah menu',
    categoryName: 'Nama kategori',
    category: 'Kategori',
    itemName: 'Nama menu',
    invalidName: 'Nama menu wajib diisi dan maksimal 80 karakter.',
    description: 'Deskripsi',
    price: 'Harga',
    invalidPrice: 'Harga harus berupa rupiah bulat yang tidak negatif.',
    imageUrl: 'URL gambar',
    sortOrder: 'Urutan',
    available: 'Tersedia',
    unavailable: 'Habis',
    active: 'Aktif',
    inactive: 'Nonaktif',
    saveCategory: 'Simpan kategori',
    saveItem: 'Simpan menu',
    savedCategory: 'Kategori berhasil disimpan.',
    savedItem: 'Menu berhasil disimpan.',
    addRecipe: 'Atur resep',
    actions: 'Aksi',
    saveRecipe: 'Simpan resep',
    recipeTitle: 'Resep menu',
    ingredient: 'Bahan',
    quantityPerServing: 'Jumlah per porsi',
    addIngredient: 'Tambah bahan',
    removeIngredient: 'Hapus bahan',
    duplicateIngredient: 'Bahan yang sama hanya boleh dicantumkan satu kali.',
    noIngredients: 'Belum ada bahan pada resep ini.',
    savedRecipe: 'Resep berhasil disimpan.',
    noCategories: 'Belum ada kategori. Buat kategori untuk memulai.',
    noItems: 'Belum ada menu pada kategori ini.',
    loadError: 'Data menu tidak dapat dimuat.',
    saveError: 'Perubahan menu belum tersimpan.',
    recipeError: 'Resep belum tersimpan.',
    inventoryUnavailable: 'Tambahkan bahan inventaris sebelum menyusun resep.',
    categoryRequired: 'Pilih kategori menu.',
    itemRequired: 'Pilih menu.',
    quantityRequired: 'Masukkan jumlah lebih dari nol.',
    inventoryLink: 'Buka inventaris',
  },
  reports: {
    title: 'Laporan penjualan',
    filters: 'Filter rentang laporan',
    datePresets: 'Periode cepat',
    today: 'Hari ini',
    last7Days: '7 hari',
    thisMonth: 'Bulan ini',
    from: 'Dari tanggal',
    to: 'Sampai tanggal',
    apply: 'Terapkan',
    rangeInvalid: 'Pilih rentang tanggal yang valid, maksimal 366 hari.',
    empty: 'Belum ada pembayaran terverifikasi pada rentang ini.',
    summary: 'Ringkasan penjualan',
    totalSales: 'Total penjualan',
    transactions: 'Transaksi',
    average: 'Rata-rata transaksi',
    refund: 'Refund',
    totalDiscount: 'Diskon voucher',
    serviceAndTax: 'Layanan dan pajak',
    void: 'Total void',
    timezoneNote: 'Dihitung dari pembayaran terverifikasi pada rentang tanggal Asia/Jakarta.',
    tabs: 'Rincian laporan',
    daily: 'Per hari',
    hourly: 'Per jam',
    method: 'Metode',
    category: 'Kategori',
    item: 'Item',
    voucher: 'Voucher',
    downloadCsv: 'Unduh CSV',
    date: 'Tanggal',
    hour: 'Jam',
    quantity: 'Jumlah',
    voucherDiscount: 'Diskon voucher',
    code: 'Kode',
    usage: 'Pemakaian',
    period: 'Periode',
    chart: 'Grafik laporan',
    methods: { cash: 'Tunai', transfer: 'Transfer', ewallet: 'E-wallet' },
  },
  errors: {
    NOT_AUTHORIZED: 'Anda tidak punya hak untuk tindakan ini.',
    INPUT_INVALID: 'Periksa kembali informasi yang dimasukkan.',
    SHIFT_NOT_OPEN: 'Belum ada shift terbuka.',
    SHIFT_ALREADY_OPEN: 'Sudah ada shift kasir yang terbuka.',
    SHIFT_NOT_FOUND: 'Shift tidak ditemukan.',
    SHIFT_HAS_OPEN_BILL: 'Tutup semua open bill terlebih dahulu.',
    ORDER_NOT_FOUND: 'Pesanan tidak ditemukan.',
    ORDER_STATUS_TRANSITION_INVALID: 'Perubahan status pesanan tidak diizinkan.',
    ORDER_NOT_CANCELLABLE: 'Pesanan tidak dapat dibatalkan pada status ini.',
    ORDER_NOT_RETURNABLE: 'Pesanan tidak dapat diretur.',
    BILL_CLOSED: 'Open bill sudah ditutup.',
    BILL_NOT_CLOSED: 'Bill belum ditutup.',
    BILL_EMPTY: 'Tambahkan item sebelum menutup bill.',
    MENU_ITEM_UNAVAILABLE: 'Menu tidak tersedia atau sedang habis.',
    ITEM_INVALID: 'Item pesanan tidak valid.',
    ITEM_QUANTITY_INVALID: 'Jumlah item harus antara 1 sampai 100.',
    ITEM_NOT_FOUND: 'Item pesanan tidak ditemukan.',
    ITEM_ALREADY_VOIDED: 'Item sudah dibatalkan.',
    MODIFIER_INVALID: 'Pilihan tambahan menu tidak valid.',
    STOCK_INSUFFICIENT: 'Stok bahan tidak mencukupi.',
    VOUCHER_NOT_FOUND: 'Kode voucher tidak ditemukan.',
    VOUCHER_INACTIVE: 'Voucher sedang tidak aktif.',
    VOUCHER_NOT_STARTED: 'Voucher belum mulai berlaku.',
    VOUCHER_EXPIRED: 'Masa berlaku voucher sudah berakhir.',
    VOUCHER_QUOTA_EXCEEDED: 'Kuota voucher sudah habis.',
    VOUCHER_MIN_SUBTOTAL: 'Belum memenuhi minimum belanja voucher.',
    VOUCHER_ALREADY_APPLIED: 'Pesanan sudah memakai voucher.',
    PAYMENT_AMOUNT_INVALID: 'Nominal pembayaran tidak valid.',
    PAYMENT_EXCEEDS_OUTSTANDING: 'Nominal pembayaran melebihi tagihan.',
    PAYMENT_ACCOUNT_INVALID: 'Rekening tidak aktif atau tidak sesuai metode.',
    PAYMENT_NOT_FOUND: 'Pembayaran tidak ditemukan.',
    PAYMENT_NOT_PENDING: 'Pembayaran sudah diverifikasi atau ditolak.',
    PAYMENT_NOT_VERIFIED: 'Pembayaran belum lunas atau belum terverifikasi.',
    CASH_RECEIVED_INSUFFICIENT: 'Uang yang diterima belum mencukupi tagihan.',
    REASON_REQUIRED: 'Alasan wajib diisi.',
    OPNAME_FINALIZED: 'Stok opname sudah difinalisasi.',
    OPNAME_NOT_FOUND: 'Stok opname tidak ditemukan.',
    OPNAME_ALREADY_DRAFT: 'Masih ada stok opname yang sedang berjalan.',
    STAFF_NOT_FOUND: 'Staff tidak ditemukan.',
    SELF_ROLE_CHANGE_FORBIDDEN: 'Anda tidak dapat mengubah peran sendiri.',
    SELF_DEACTIVATION_FORBIDDEN: 'Anda tidak dapat menonaktifkan akun sendiri.',
    LAST_SUPER_ADMIN: 'Super admin terakhir tidak dapat dinonaktifkan atau diturunkan perannya.',
    SETTINGS_INVALID: 'Pengaturan tidak valid.',
    CONTRAST_TOO_LOW: 'Kontras warna di bawah standar aksesibilitas.',
    STAFF_EMAIL_EXISTS: 'Email sudah terdaftar.',
    SERVER_NOT_CONFIGURED: 'Konfigurasi layanan belum lengkap. Hubungi pemilik.',
    NETWORK_OFFLINE: 'Koneksi internet terputus.',
    REQUEST_TIMEOUT: 'Koneksi lambat. Coba lagi.',
    UNKNOWN: 'Terjadi kesalahan. Coba lagi.',
    INVALID_CREDENTIALS: 'Email atau kata sandi salah.',
    PASSWORD_CURRENT_INVALID: 'Kata sandi saat ini tidak sesuai.',
    NOT_FOUND: 'Halaman tidak ditemukan.',
    forbiddenTitle: 'Anda tidak punya akses.',
    backToShift: 'Kembali ke shift kasir',
  },
} as const;
