create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create type role_type as enum ('super_admin', 'admin');
create type order_type as enum ('dine_in', 'takeaway');
create type order_status as enum ('new', 'processing', 'ready', 'completed', 'cancelled');
create type bill_state as enum ('open', 'closed');
create type payment_method as enum ('cash', 'transfer', 'ewallet');
create type payment_status as enum ('pending_verification', 'verified', 'rejected');
create type voucher_type as enum ('percent', 'nominal');
create type movement_type as enum ('purchase', 'sale', 'void_return', 'cancel_return', 'adjustment', 'opname', 'waste');
create type shift_status as enum ('open', 'closed');
create type opname_status as enum ('draft', 'finalized');

create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text not null,
  role role_type not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table store_settings (
  id int primary key default 1 check (id = 1),
  store_name text not null,
  address text,
  phone text,
  logo_url text,
  primary_color text not null default '#6F4E37',
  accent_color text not null default '#F5E6D3',
  font_family text not null default 'Inter' check (font_family in ('Inter', 'Plus Jakarta Sans', 'Poppins', 'system-ui')),
  tax_percent numeric(5, 2) not null default 0 check (tax_percent between 0 and 100),
  service_percent numeric(5, 2) not null default 0 check (service_percent between 0 and 100),
  rounding_rule text not null default 'none' check (rounding_rule in ('none', 'up_100', 'nearest_100')),
  receipt_header text,
  receipt_footer text,
  paper_width_mm int not null default 58 check (paper_width_mm in (58, 80)),
  require_verified_payment boolean not null default true,
  updated_by uuid references profiles(id),
  updated_at timestamptz not null default now()
);

insert into store_settings (id, store_name)
values (1, 'JOKGER')
on conflict (id) do nothing;

create table payment_accounts (
  id uuid primary key default gen_random_uuid(),
  method payment_method not null check (method in ('transfer', 'ewallet')),
  provider text not null,
  account_name text not null,
  account_no text not null check (account_no ~ '^[0-9]+$'),
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references profiles(id),
  action text not null,
  entity text not null,
  entity_id text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create table categories (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  sort_order int not null default 0,
  is_active boolean not null default true
);

create table menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references categories(id),
  name text not null,
  description text,
  price bigint not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table modifier_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  min_select int not null default 0,
  max_select int not null default 1,
  check (min_select >= 0 and max_select >= min_select)
);

create table modifier_options (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references modifier_groups(id) on delete cascade,
  name text not null,
  extra_price bigint not null default 0 check (extra_price >= 0),
  is_active boolean not null default true
);

create table menu_item_modifier_groups (
  menu_item_id uuid not null references menu_items(id) on delete cascade,
  group_id uuid not null references modifier_groups(id) on delete cascade,
  primary key (menu_item_id, group_id)
);

create table inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  unit text not null,
  current_qty numeric(14, 3) not null default 0,
  min_qty numeric(14, 3) not null default 0,
  unit_cost bigint not null default 0 check (unit_cost >= 0),
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table recipe_lines (
  menu_item_id uuid not null references menu_items(id) on delete cascade,
  inventory_item_id uuid not null references inventory_items(id),
  qty_per_serving numeric(14, 3) not null check (qty_per_serving > 0),
  primary key (menu_item_id, inventory_item_id)
);

create table stock_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id uuid not null references inventory_items(id),
  movement_type movement_type not null,
  qty_change numeric(14, 3) not null check (qty_change <> 0),
  reference_type text,
  reference_id text,
  note text,
  actor_id uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table stock_opnames (
  id uuid primary key default gen_random_uuid(),
  status opname_status not null default 'draft',
  opened_by uuid references profiles(id),
  opened_at timestamptz not null default now(),
  finalized_at timestamptz
);

create table stock_opname_lines (
  opname_id uuid not null references stock_opnames(id) on delete cascade,
  inventory_item_id uuid not null references inventory_items(id),
  system_qty numeric(14, 3) not null,
  counted_qty numeric(14, 3),
  primary key (opname_id, inventory_item_id)
);

create table shifts (
  id uuid primary key default gen_random_uuid(),
  status shift_status not null default 'open',
  opened_by uuid not null references profiles(id),
  opened_at timestamptz not null default now(),
  opening_cash bigint not null check (opening_cash >= 0),
  closed_by uuid references profiles(id),
  closed_at timestamptz,
  expected_cash bigint,
  actual_cash bigint,
  difference bigint,
  note text
);

create unique index one_open_shift on shifts ((true)) where status = 'open';

create table daily_sequences (
  day date primary key,
  last_no int not null default 0
);

create table vouchers (
  id uuid primary key default gen_random_uuid(),
  code text unique not null check (code = upper(code) and code ~ '^[A-Z0-9-]{3,32}$'),
  name text not null,
  type voucher_type not null,
  value bigint not null check (value > 0),
  min_subtotal bigint not null default 0 check (min_subtotal >= 0),
  max_discount bigint check (max_discount is null or max_discount > 0),
  valid_from timestamptz not null,
  valid_until timestamptz not null,
  total_quota int check (total_quota is null or total_quota > 0),
  used_count int not null default 0 check (used_count >= 0),
  is_active boolean not null default true,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  check (valid_until > valid_from),
  check (type <> 'percent' or value between 1 and 100)
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  order_no text unique not null,
  shift_id uuid not null references shifts(id),
  order_type order_type not null,
  status order_status not null default 'new',
  bill_state bill_state,
  table_label text,
  customer_name text,
  subtotal bigint not null default 0 check (subtotal >= 0),
  discount_total bigint not null default 0 check (discount_total >= 0),
  service_amount bigint not null default 0,
  tax_amount bigint not null default 0,
  rounding_amount bigint not null default 0,
  grand_total bigint not null default 0 check (grand_total >= 0),
  voucher_id uuid references vouchers(id),
  voucher_code text,
  cancelled_from order_status,
  cancel_reason text,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  check (status <> 'cancelled' or cancel_reason is not null)
);

create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  menu_item_id uuid not null references menu_items(id),
  item_name text not null,
  unit_price bigint not null check (unit_price >= 0),
  modifiers jsonb not null default '[]'::jsonb,
  qty int not null check (qty between 1 and 100),
  line_total bigint not null check (line_total >= 0),
  note text,
  is_voided boolean not null default false,
  void_reason text,
  voided_by uuid references profiles(id),
  voided_at timestamptz,
  created_at timestamptz not null default now()
);

create table voucher_redemptions (
  id uuid primary key default gen_random_uuid(),
  voucher_id uuid not null references vouchers(id),
  order_id uuid not null unique references orders(id),
  discount bigint not null,
  created_at timestamptz not null default now()
);

create table payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id),
  shift_id uuid not null references shifts(id),
  method payment_method not null,
  payment_account_id uuid references payment_accounts(id),
  amount bigint not null check (amount <> 0),
  received_amount bigint check (received_amount is null or received_amount >= 0),
  change_amount bigint not null default 0 check (change_amount >= 0),
  is_refund boolean not null default false,
  status payment_status not null default 'pending_verification',
  reference_no text,
  proof_path text,
  note text,
  verified_by uuid references profiles(id),
  verified_at timestamptz,
  created_by uuid not null references profiles(id),
  created_at timestamptz not null default now(),
  check ((is_refund and amount < 0) or (not is_refund and amount > 0)),
  check (method <> 'cash' or payment_account_id is null),
  check (method = 'cash' or payment_account_id is not null or is_refund)
);

create table client_requests (
  client_ref uuid primary key,
  rpc_name text not null,
  result_id uuid,
  created_at timestamptz not null default now()
);

create index orders_status_created_at_idx on orders (status, created_at);
create index orders_shift_id_idx on orders (shift_id);
create index orders_open_bill_idx on orders (bill_state) where bill_state = 'open';
create index order_items_order_id_idx on order_items (order_id);
create index payments_order_id_idx on payments (order_id);
create index payments_shift_method_status_idx on payments (shift_id, method, status);
create index payments_created_at_idx on payments (created_at);
create index stock_movements_item_created_at_idx on stock_movements (inventory_item_id, created_at);
create index audit_logs_entity_idx on audit_logs (entity, entity_id);
create index audit_logs_created_at_idx on audit_logs (created_at);

create function current_role_type()
returns role_type
language sql
stable
security definer
set search_path = public
as $$
  select role from profiles where id = auth.uid() and is_active;
$$;

create function is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select current_role_type() is not null;
$$;

create function is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select current_role_type() = 'super_admin';
$$;

revoke all on function current_role_type() from public, anon;
revoke all on function is_staff() from public, anon;
revoke all on function is_super_admin() from public, anon;
grant execute on function current_role_type() to authenticated;
grant execute on function is_staff() to authenticated;
grant execute on function is_super_admin() to authenticated;

alter table profiles enable row level security;
alter table store_settings enable row level security;
alter table payment_accounts enable row level security;
alter table audit_logs enable row level security;
alter table categories enable row level security;
alter table menu_items enable row level security;
alter table modifier_groups enable row level security;
alter table modifier_options enable row level security;
alter table menu_item_modifier_groups enable row level security;
alter table inventory_items enable row level security;
alter table recipe_lines enable row level security;
alter table stock_movements enable row level security;
alter table stock_opnames enable row level security;
alter table stock_opname_lines enable row level security;
alter table shifts enable row level security;
alter table daily_sequences enable row level security;
alter table vouchers enable row level security;
alter table voucher_redemptions enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table payments enable row level security;
alter table client_requests enable row level security;

create policy profiles_read_staff on profiles for select to authenticated using (is_staff());
create policy store_settings_read_public on store_settings for select to anon, authenticated using (true);
create policy payment_accounts_read_staff on payment_accounts for select to authenticated using (is_staff());
create policy audit_logs_read_super_admin on audit_logs for select to authenticated using (is_super_admin());
create policy categories_read_staff on categories for select to authenticated using (is_staff());
create policy menu_items_read_staff on menu_items for select to authenticated using (is_staff());
create policy modifier_groups_read_staff on modifier_groups for select to authenticated using (is_staff());
create policy modifier_options_read_staff on modifier_options for select to authenticated using (is_staff());
create policy menu_item_modifier_groups_read_staff on menu_item_modifier_groups for select to authenticated using (is_staff());
create policy inventory_items_read_staff on inventory_items for select to authenticated using (is_staff());
create policy recipe_lines_read_staff on recipe_lines for select to authenticated using (is_staff());
create policy stock_movements_read_staff on stock_movements for select to authenticated using (is_staff());
create policy stock_opnames_read_staff on stock_opnames for select to authenticated using (is_staff());
create policy stock_opname_lines_read_staff on stock_opname_lines for select to authenticated using (is_staff());
create policy shifts_read_staff on shifts for select to authenticated using (is_staff());
create policy vouchers_read_staff on vouchers for select to authenticated using (is_staff());
create policy voucher_redemptions_read_staff on voucher_redemptions for select to authenticated using (is_staff());
create policy orders_read_staff on orders for select to authenticated using (is_staff());
create policy order_items_read_staff on order_items for select to authenticated using (is_staff());
create policy payments_read_staff on payments for select to authenticated using (is_staff());

revoke all on all tables in schema public from anon, authenticated;
grant select on profiles, store_settings, payment_accounts, audit_logs, categories, menu_items,
  modifier_groups, modifier_options, menu_item_modifier_groups, inventory_items, recipe_lines,
  stock_movements, stock_opnames, stock_opname_lines, shifts, vouchers,
  voucher_redemptions, orders, order_items, payments to authenticated;
grant select on store_settings to anon;
revoke all on all sequences in schema public from anon, authenticated;

grant usage on schema public to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('payment-proofs', 'payment-proofs', false, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('public-assets', 'public-assets', true, 1048576, array['image/png', 'image/svg+xml', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy payment_proofs_read_staff on storage.objects
for select to authenticated using (bucket_id = 'payment-proofs' and public.is_staff());
create policy payment_proofs_insert_staff on storage.objects
for insert to authenticated with check (bucket_id = 'payment-proofs' and public.is_staff());
create policy public_assets_read_public on storage.objects
for select to anon, authenticated using (bucket_id = 'public-assets');
create policy public_assets_insert_staff on storage.objects
for insert to authenticated with check (bucket_id = 'public-assets' and public.is_staff());
